config/routes.rb
Rails.application.routes.draw do

   root 'pages#home'
   get 'about', to: 'pages#about'
    
    resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
    validates :title, presence:true , length:{minimum:3, maximum:50}
    validates :description, presence:true , length:{minimum:10, maximum:300}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
   
   def index
    @article = Article.all    
   end
   
   def new 
    @article = Article.new
   end
   
   def create 
    @article = Article.new(article_params)
    if @article.save
        flash[:notice] = "Article was successfully created"
        redirect_to article_path(@article)
    else
        render 'new'
    end
   end
   
   def show 
       @article = Article.find(params[:id])
   end
   
   def destroy 
       @article = Article.find(params[:id]) 
       @article.destroy 
       flash[:notice] = "Article was successfully deleted"
       redirect_to articles_path
   end
   
   def edit
       @article = Article.find(params[:id])
   end
   
   def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            flash[:notice] = "Article was successfully Updated"
            redirect_to article_path(@article)
        else
            render 'edit'
        end
   end
   
   private 
    def article_params
        params.require(:article).permit(:title,:description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
   
   def home
       
   end
   
   def about 
       
   end
   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
    <h3> Please correct the below errors </h3>
    <ul>
    <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
    <% end %>
    </ul>
<% end %>

<%= form_for @article do |x| %>
    <p>
        <%= x.label :title %> <br>
        <%= x.text_field :title %> 
    </p>
    <p>
        <%= x.label :description %> <br>
        <%= x.text_area :description %>
    </p>
    <p>
       <%= x.submit %> 
    </p>
<% end %>

<p>
    <%= link_to 'Back to Articles listing', articles_path %>
</p>

app/views/articles/edit.html.erb
<h1> Edit Article </h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1> All Articles </h1>
<p>
    <%= link_to 'Create New', new_article_path %>
</p>
<table>
    <tr>
        <th>ID</th>
        <th>Title</th>
        <th>Description</th>
    </tr>
    <tr>
        <td>
            
        </td>
    </tr>
    <% @article.each do |a| %>
    <tr>
        <td><%= a.id %></td>
        <td><%= a.title %></td>
        <td><%= a.description %></td>
        <td> <%= link_to 'Show', article_path(a) %></td>
        <td> <%= link_to 'Edit', edit_article_path(a) %></td>
        <td> <%= link_to 'Delete', article_path(a) , method: :delete , data: {confirm: "Are You Sure?"} %></td>
    </tr>
    <% end %>
</table>

app/views/articles/new.html.erb
<h1> Create New Article </h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h1> This is selected Article </h1>

<p>
    Title: <%= @article.title %>
</p>
<p> 
    Description: <%= @article.description %>
</p>

<p>
    <%= link_to 'Edit', edit_article_path(@article) %>
    |
    <%= link_to 'Back to Articles listing', articles_path %>
</p>

app/views/articles/update.html.erb
<h1> Article updated </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yusuf Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% flash.each do |name,msg| %>
  <%= msg %>
<% end %>
<%= yield %>

</body>
</html>

app/views/pages/about.html.erb
<html>
    <head>
        <title> About My Blog</title>
    </head>
    <body>
        <h1>
            This is my About page of Blog!
        </h1>
        <%= link_to 'Home' , root_path %>
    </body>
</html>

app/views/pages/home.html.erb
<html>
    <head>
        <title> Welcome to My Blog</title>
    </head>
    <body>
        <h1>
            This is my Home page of Blog!
        </h1>
        <%= link_to 'Yusuf Blog' , articles_path %> |
        <%= link_to 'About' , about_path %>
    </body>
</html>